name: Build Test

on: [ push, pull_request ]

env:
  IS_CI_BUILD: 'true'

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Delete previous installed tools
        run: rm -rf /opt/hostedtoolcache
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Gradle Build
        run: ./gradlew :buildPlugin -PbuildType=stable
      - name: Gradle Test
        run: ./gradlew :test --tests "jezzsantos.automate.*"
