name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-preview'

env:
  IS_CI_BUILD: 'true'
  ORG_GRADLE_PROJECT_intellijPublishToken: ${{secrets.JETBRAINSPLUGINMARKETPLACE}}
  APPLICATIONINSIGHTS_INSTRUMENTATIONKEY: ${{secrets.APPLICATIONINSIGHTS_INSTRUMENTATIONKEY}}

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Delete previous installed tools
        run: rm -rf /opt/hostedtoolcache
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Update Secrets
        run: echo applicationInsightsInstrumentationKey="$APPLICATIONINSIGHTS_INSTRUMENTATIONKEY" > src/main/resources/application.properties
      - name: Gradle Build
        run: ./gradlew :buildPlugin -PbuildType=stable
      - name: Gradle Publish to Marketplace
        run: ./gradlew :publishPlugin
